Pytest
pysprings/Pysprings_Badging_System pull request #20
Opened 2018-09-26 19:18 UTC by kajuberdut

Travis branch for #6 and the pytest branch for #4. I would have liked to keep these separate but apparently I'll need to find a GUI for git because it is opaque to me.

2018-09-26 23:32 UTC, gp-tmcfadden requested changes
Looks fine once you fix `.vscode`.

2018-09-26 23:32 UTC, gp-tmcfadden commented on .vscode/settings.json
> +{
Definitely remove this file from src code control.  Please add `.vscode` to `.gitignore` while you're at it.

2018-09-26 23:32 UTC, gp-tmcfadden commented on Makefile
> +help:
`Makefile`?  That's old school!

2018-09-26 23:32 UTC, gp-tmcfadden commented on Pipfile.lock
>              ],
This is why we need to change `Pipfile` to lock down do a certain version of Django (IMO)

2018-10-24 00:55 UTC, mtik00 approved these changes
LGTM

2018-10-24 00:55 UTC, merged